Improved error handling in zmtest

diff --git a/zmtest b/zmtest
--- a/zmtest
+++ b/zmtest
@@ -10,16 +10,26 @@ usage_error () {
     exit 2
 }
 
+zmb () {
+    json="`"${ZMB}" "$@"`"
+    if echo "$json" | jq -e .error > /dev/null ; then
+        echo "error: method $1: $json" >& 2
+        exit 1
+    else
+        echo "$json"
+    fi
+}
+
 [ $# -ge 1 ] || usage_error "No domain specified"
 domain="$1" ; shift
 
 # Start test
-testid="`"${ZMB}" start_domain_test --domain "$domain" | jq -r .result`"
+testid="`zmb start_domain_test --domain "$domain" | jq -r .result`" || exit 1
 
 # Wait for test to finish
 while true
 do
-    progress="`"${ZMB}" test_progress --testid "$testid" | jq -r .result`"
+    progress="`zmb test_progress --testid "$testid" | jq -r .result`" || exit 1
     echo -n "\r$progress% done" >&2
     if [ "$progress" -eq 100 ] ; then
         echo >&2
@@ -29,5 +39,5 @@ do
 done
 
 # Get test results
-"${ZMB}" get_test_results --testid "$testid" --lang en
+zmb get_test_results --testid "$testid" --lang en
 echo "testid:" $testid >&2
