Tidy and refactor

diff --git a/zmtest b/zmtest
--- a/zmtest
+++ b/zmtest
@@ -2,39 +2,39 @@
 
 bindir="`dirname $0`"
 
-ZMB="$bindir/zmb"
+ZMB="${bindir}/zmb"
 JQ="`which jq`"
 
 error () {
-    message="$1"
-    echo "$message" >&2
-    exit 2
+    status="$1"
+    message="$2"
+    echo "error: ${message}" >&2
+    exit "${status}"
 }
 
 zmb () {
     json="`"${ZMB}" "$@"`"
-    if echo "$json" | jq -e .error > /dev/null ; then
-        echo "error: method $1: $json" >& 2
-        exit 1
+    if echo "${json}" | "${JQ}" -e .error > /dev/null ; then
+        error 1 "method $1: ${json}"
     else
-        echo "$json"
+        echo "${json}"
     fi
 }
 
-[ -n "${JQ}" ] || error "Dependency not found: jq"
+[ -n "${JQ}" ] || error 2 "Dependency not found: jq"
 
-[ $# -ge 1 ] || error "No domain specified"
+[ $# -ge 1 ] || error 2 "No domain specified"
 domain="$1" ; shift
 
 # Start test
-testid="`zmb start_domain_test --domain "$domain" | jq -r .result`" || exit 1
+testid="`zmb start_domain_test --domain "${domain}" | "${JQ}" -r .result`" || exit 1
 
 # Wait for test to finish
 while true
 do
-    progress="`zmb test_progress --testid "$testid" | jq -r .result`" || exit 1
-    printf "\r$progress%% done" >&2
-    if [ "$progress" -eq 100 ] ; then
+    progress="`zmb test_progress --testid "${testid}" | "${JQ}" -r .result`" || exit 1
+    printf "\r${progress}%% done" >&2
+    if [ "${progress}" -eq 100 ] ; then
         echo >&2
         break
     fi
@@ -42,5 +42,5 @@ do
 done
 
 # Get test results
-zmb get_test_results --testid "$testid" --lang en
-echo "testid:" $testid >&2
+zmb get_test_results --testid "${testid}" --lang en
+echo "testid:" ${testid} >&2
